### ISSUE TITLE
when I run the code I got the problem,  how should I fix it 

### ISSUE THREAD

**Issue by luhc15** [knorth55/chainer-fcis#19]
File "/home/luhongchao/chainer/chainer-fcis/fcis/mask.py", line 134, in intersect_bbox_mask
    gt_roi_mask[start_y:end_y, start_x:end_x] = gt_clipped_mask
ValueError: could not broadcast input array from shape (153,0) into shape (153,262)

**Comment by knorth55** [comment]
Can you print your `bbox`, `gt_bbox` when it raises this error?

**Comment by luhc15** [comment]
yeah ,  I print the value of bbox, gt_bbox like this :
bbox:  [ 67  -1 597 796]
gt_bbox:  [ 67  -1 597 796]
gt_mask: [[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]] (600, 800)
gt_clipped_mask:  []
the  value of bbox is the same as gt_bbox, and a negative value of bbox[1]

**Comment by knorth55** [comment]
> the value of bbox is the same as gt_bbox, and a negative value of bbox[1]

the reason of this error is this negative value.
Are you training with your own dataset?
`gt_bbox` do not accept negative value.

**Comment by luhc15** [comment]
I trained with VOC2012, but the same problem encountered in VOC2007, I haven't figured out the reason

**Comment by knorth55** [comment]
hmmm, that's weird.
In my PC, I have no issue on training.
Are you using SBD dataset for VOC2012 training?
I want to know how you execute training script.
```
cd examples/voc/
python train.py
```

**Comment by knorth55** [comment]
And also, do you use the latest master branch?

**Comment by luhc15** [comment]
yes I cloned the latest repository and tried again, the same issue emerged,  it's really weird . I use script: 
cd examples/voc/  python train.py 
and change dataset SBD, it does not work too.

**Comment by knorth55** [comment]
Hmmm, thats really weird....
but gt_bbox ahould not have negative value, so there is aomething wrong around dataset.
i will work on this issue next week.

**Comment by knorth55** [comment]
@luhc15 I tried again and again, but I can't reproduce your error.
If possible, can you paste all your env info, like python, chainer, cupy, cuda and cudnn version?

**Comment by luhc15** [comment]
thanks very much, the env info is: 
 Python 2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
>>> print numpy.__version__
1.13.3
>>> print scipy.__version__
1.0.0
>>> print chainer.__version__
3.0.0
>>> print cupy.__version__
2.0.0
CUDA Version 8.0.61
CUDNN Version: 5.1.10

**Comment by betterhalfwzm** [comment]
I have the same problem ,do you have solve it?@luhc15 @knorth55  @luhc15

**Comment by knorth55** [comment]
@betterhalfwzm can you install `chainercv` from source?

```
git clone https://github.com/chainer/chainercv.git
cd chainercv
pip install -e .
```

I'm not sure, but we need this https://github.com/chainer/chainercv/pull/458.

**Comment by betterhalfwzm** [comment]
@knorth55 I do like this:
$ pip install -U numpy
$ pip install chainercv .
I have a try 
git clone https://github.com/chainer/chainercv.git
cd chainercv
pip install -e .
it works.Tks a lot!!!

**Comment by knorth55** [comment]
@luhc15 your problem is also same, i think.
can you try to install `chainercv` from `source`?
